"""auto-vote

Revision ID: 143a6e6d3d05
Revises: d7fbb4cf97d3
Create Date: 2023-03-06 22:11:15.133647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143a6e6d3d05'
down_revision = 'd7fbb4cf97d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
